# Generated by Django 4.0.3 on 2022-06-16 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodyQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(max_length=50)),
                ('answer_2', models.CharField(max_length=50)),
                ('answer_3', models.CharField(max_length=50)),
                ('answer_4', models.CharField(max_length=50)),
                ('answer_5', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='HomeQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_1', models.CharField(max_length=50)),
                ('answer_2', models.CharField(max_length=50)),
                ('answer_3', models.CharField(max_length=50)),
                ('answer_4', models.CharField(max_length=50)),
                ('answer_5', models.CharField(max_length=50)),
                ('created', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('sku', models.CharField(max_length=12, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('image', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='UserVO',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('import_href', models.CharField(max_length=200, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='WishList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to='customer_rest.productvo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_rest.uservo')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField()),
                ('totals', models.DecimalField(decimal_places=2, max_digits=5)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='customer_rest.productvo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_rest.uservo')),
            ],
        ),
    ]
