# Generated by Django 4.0.3 on 2022-06-22 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='totals',
        ),
    ]
