# Generated by Django 4.0.3 on 2022-06-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='scent',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
