# Generated by Django 4.0.3 on 2022-06-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uservo',
            name='user',
            field=models.CharField(default='Nick', max_length=50),
            preserve_default=False,
        ),
    ]
