# Generated by Django 4.0.3 on 2022-06-03 23:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customer_rest', '0003_scentvo_productvo_image_productvo_import_href_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='scent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer_rest.scentvo'),
        ),
    ]
