# Generated by Django 4.0.3 on 2022-06-20 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_rest', '0004_alter_productvo_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyquiz',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='homequiz',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='wishlist',
            name='user',
            field=models.IntegerField(null=True),
        ),
    ]
