# Generated by Django 4.0.3 on 2022-06-06 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer_rest', '0004_alter_answer_scent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='scent',
        ),
        migrations.DeleteModel(
            name='ScentVO',
        ),
    ]
