# Generated by Django 4.0.3 on 2022-06-22 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_rest', '0005_bodyquiz_user_homequiz_user_alter_cart_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
