# Generated by Django 4.0.3 on 2022-06-23 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee_rest', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='productvo',
            name='limited_item',
        ),
        migrations.DeleteModel(
            name='UserVO',
        ),
    ]
