# Generated by Django 4.0.3 on 2022-06-24 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee_rest", "0004_alter_lineitem_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="productvo",
            name="image",
            field=models.URLField(null=True),
        ),
    ]
