FROM python:3.10-bullseye
RUN python -m pip install --upgrade pip
WORKDIR /app

# Copy the top-level files
COPY poll/requirements.txt requirements.txt
COPY poll/poller.py poller.py

# Copy the Django project and all Django apps
COPY api/customer_project customer_project
COPY api/customer_rest customer_rest
COPY api/common common

RUN pip install -r requirements.txt
CMD python poller.py
