# Generated by Django 4.0.3 on 2022-06-01 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('sku', models.CharField(max_length=12, unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rating', models.PositiveSmallIntegerField()),
                ('size', models.PositiveSmallIntegerField()),
                ('quantity', models.PositiveSmallIntegerField()),
                ('tags', models.CharField(max_length=50)),
                ('ingredients', models.CharField(max_length=100)),
                ('limited_item', models.BooleanField()),
                ('created', models.DateTimeField()),
                ('image', models.URLField()),
                ('description', models.CharField(max_length=400)),
                ('usage', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Scent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scents', models.CharField(choices=[('Fresh', 'Fresh'), ('Amber', 'Amber'), ('Floral', 'Floral'), ('Woody', 'Woody'), ('Fruity', 'Fruity'), ('Gourmand', 'Gourmand')], default='Fresh', max_length=25)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scents', to='inventory_rest.product')),
            ],
        ),
    ]
