# Generated by Django 4.0.3 on 2022-06-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0002_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('', '-----------'), ('Home', 'Home'), ('Body', 'Body')], default='', max_length=10),
        ),
    ]
