# Generated by Django 4.0.3 on 2022-06-08 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_rest", "0003_product_product_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="scent3",
        ),
        migrations.RemoveField(
            model_name="product",
            name="scent4",
        ),
        migrations.AlterField(
            model_name="product",
            name="scent1",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "-----------"),
                    ("Fresh", "Fresh"),
                    ("Amber", "Amber"),
                    ("Floral", "Floral"),
                    ("Woody", "Woody"),
                    ("Fruity", "Fruity"),
                    ("Gourmand", "Gourmand"),
                ],
                max_length=25,
            ),
        ),
    ]
