# Generated by Django 4.0.3 on 2022-06-08 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0004_remove_product_scent3_remove_product_scent4_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_category',
            field=models.CharField(choices=[('', '-----------'), ('Candle', 'Candle'), ('Incense Stick', 'Incense Stick'), ('Room Spray', 'Room Spray'), ('Lotion', 'Lotion'), ('Body Wash', 'Body Wash'), ('Soap', 'Soap'), ('Deodorant', 'Deodorant')], default='', max_length=25),
        ),
    ]
