# Generated by Django 4.0.3 on 2022-06-08 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0008_alter_product_size_delete_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_type',
            field=models.CharField(choices=[('', '-----------'), ('Home', 'Home'), ('Body', 'Body')], default='', max_length=50),
        ),
    ]
