# Generated by Django 4.0.3 on 2022-06-09 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_rest", "0010_product_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="status",
        ),
    ]
