# Generated by Django 4.0.3 on 2022-06-24 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_rest', '0011_remove_product_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('id', 'name')},
        ),
    ]
